# ╔══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ EC2 Dev Environment For Remote SSH Stack - CloudFormation Template                                                                               ║
# ╚══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 Dev Environment For Remote SSH Stack."
Transform:
  - "AWS::LanguageExtensions"

Metadata:
  AWS::Cloudformation::Interface:
    ParameterGroups:
      - Label:
          defalt: NW Settings.
        Parameters:
          - VpcCidr
          - PublicSubnet1aCidr
      - Lablel:
          default: EC2 Settings.
        Parameters:
          - LatestAmiId
          - InstanceType
          - RootVolumeSize

# ╔══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ EC2 Dev Environment For Remote SSH Stack - CloudFormation Template Parameters                                                                    ║
# ╠═══════════════════════════════════════╤═════════════════════════════════════════════════╤════════════════════════════════════════════════════════╣
# ║ VpcCidr                               │ String                                          │ VPC Cidr.                                              ║
# ║ PublicSubnet1aCidr                    │ String                                          │ Public Subnet AZ-A Cidr.                               ║
# ║ LatestAmiId                           │ AWS::SSM::Parameter::Value<AWS::EC2::Image::Id> │ Latest Amazon Linux 2023 Ami ID.                       ║
# ║ InstanceType                          │ String                                          │ Instance Type.                                         ║
# ║ RootVolumeSize                        │ Number                                          │ RootVolumeSize.                                        ║
# ╚═══════════════════════════════════════╧═════════════════════════════════════════════════╧════════════════════════════════════════════════════════╝
Parameters:
  VpcCidr:
    Description: VPC Cidr
    Type: String

  PublicSubnet1aCidr:
    Description: Public Subnet AZ-A Cidr
    Type: String

  LatestAmiId:
    Description: Latest Amazon Linux 2023 AMI ID.
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64

  InstanceType:
    Description: EC2 Instance Type.
    Type: String

  RootVolumeSize:
    Description: EC2 Instance Root Volume Size.
    Type: Number

# ╔══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ EC2 Dev Environment For Remote SSH Stack - CloudFormation Template Mappings                                                                      ║
# ╠═════════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╣
# ║ VpcParams           │ VPC Paramters.                                                                                                             ║
# ║ IgwParams           │ Internet Gateway Paramters.                                                                                                ║
# ║ SubnetParams        │ Subnet Paramters.                                                                                                          ║
# ║ NaclParams          │ NACL Paramters.                                                                                                            ║
# ║ RtbParams           │ RouteTable Paramters.                                                                                                      ║
# ║ IamParams           │ IAM Paramters.                                                                                                             ║
# ║ SgParams            │ SecurityGroup Paramters.                                                                                                   ║
# ║ EpParams            │ VPC Interface Endpoint Paramters.                                                                                          ║
# ║ KeyPairParams       │ KeyPair Paramters.                                                                                                         ║
# ║ Ec2Params           │ EC2 Instance Paramters.                                                                                                    ║
# ╚═════════════════════╧════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
Mappings:
  VpcParams:
    VpcType:
      Name: dev-vpc
      DnsHost: true
      DnsSupport: true
      Cidr: VpcCidr
  IgwParams:
    IgwType:
      Name: dev-igw
  SubnetParams:
    PublicSubnet1a:
      Name: dev-public-subnet-a
      Cidr: PublicSubnet1aCidr
  NaclParams:
    NaclType:
      Name: dev-nacl
    Association:
      AssocSubnet1: PublicSubnet1a
  RtbParams:
    RtbType:
      RtbPublic: dev-public-rtb
    PublicAssociation:
      RtbAssocPublicSubnet1: PublicSubnet1a
  IamParams:
    IamType:
      Description: IAM Role for EC2 Instance.
      Name: dev-iam-role-ec2
  SgParams:
    SgType:
      Ec2Sg: dev-ec2-sg
  KeyPairParams:
    KeyPairType:
      Name: dev-keypair
  Ec2Params:
    Instance1:
      Name: dev-ec2-instance
      AmiId: LatestAmiId
      InstanceType: InstanceType
      RootVolumeSize: RootVolumeSize
      SgName: Ec2Sg
      SubnetName: PublicSubnet1a
      DeviceName: /dev/xvda
      KeyPairName: KeyPair

# ╔══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ EC2 Dev Environment For Remote SSH Stack - CloudFormation Template Resources                                                                     ║
# ╠═════════════════════════════════════╤═══════════════════════════════════════════╤════════════════════════════════════════════════════════════════╣
# ║ Vpc                                 │ AWS::EC2::VPC                             │ VPC.                                                           ║
# ║ Igw                                 │ AWS::EC2::InternetGateway                 │ InternetGateway.                                               ║
# ║ IgwAttach                           │ AWS::EC2::VPCGatewayAttachment            │ InternetGateway Attachment.                                    ║
# ║ PublicSubnet1a                      │ AWS::EC2::Subnet                          │ Public Subnet AZ-A.                                            ║
# ║ Nacl                                │ AWS::EC2::NetworkAcl                      │ All Allow NACL.                                                ║
# ║ NaclInEntry100                      │ AWS::EC2::NetworkAclEntry                 │ All Allow Inbound Entry.                                       ║
# ║ NaclOutEntry100                     │ AWS::EC2::NetworkAclEntry                 │ All Allow Outbound Entry.                                      ║
# ║ AssocSubnet1                        │ AWS::EC2::SubnetNetworkAclAssociation     │ NACL Association.                                              ║
# ║ RtbPublic                           │ AWS::EC2::RouteTable                      │ Public Subnet RouteTable.                                      ║
# ║ RtbAssocPublicSubnet1               │ AWS::EC2::SubnetRouteTableAssociation     │ RouteTable Association Public Subnet.                          ║
# ║ S3GwEp                              │ AWS::EC2::VPCEndpoint                     │ S3 Gateway Endpoint.                                           ║
# ║ RtbPublicEntry1                     │ AWS::EC2::Route                           │ RouteTable Entry 1.                                            ║
# ║ Role                                │ AWS::IAM::Role                            │ EC2 IAM Role.                                                  ║
# ║ InstanceProfile                     │ AWS::IAM::InstanceProfile                 │ EC2 IAM InstanceProfile.                                       ║
# ║ Ec2Sg                               │ AWS::EC2::SecurityGroup                   │ EC2 SecurityGroup.                                             ║
# ║ KeyPair                             │ AWS::EC2::KeyPair                         │ KeyPair.                                                       ║
# ║ Ec2Instance                         │ AWS::EC2::Instance                        │ EC2 Instance.                                                  ║
# ╚═════════════════════════════════════╧═══════════════════════════════════════════╧════════════════════════════════════════════════════════════════╝
Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref
        "Fn::FindInMap": [VpcParams, VpcType, Cidr]
      EnableDnsHostnames: !FindInMap [VpcParams, VpcType, DnsHost]
      EnableDnsSupport: !FindInMap [VpcParams, VpcType, DnsSupport]
      Tags:
        - Key: Name
          Value: !FindInMap [VpcParams, VpcType, Name]

  Igw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !FindInMap [IgwParams, IgwType, Name]

  IgwAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref Igw
